env:
  browser: true
  es2021: true
  jest: true
  node: true
extends:
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  semi: [2, always]
  indent: ["error", 4]